#pragma once
// Generated by tools/train_selector_model.py from measured benchmark data.
// Do not edit by hand.

#include <cstddef>
#include <cstdint>

namespace my_ptmalloc::generated_selector_model {

static constexpr const char* MODEL_ID = "learned_cost_gbdt_v3_n784_t70";
static constexpr size_t FEATURE_COUNT = 10;
static constexpr size_t TREE_COUNT = 70;
static constexpr double SWITCH_COST = 0.0101525439468;

enum Feature : uint8_t {
    LargeBytesRatio = 0,
    RemoteFreeRatio = 1,
    MappedLiveRatio = 2,
    SlowPathRatio = 3,
    SizeEntropy = 4,
    InternalFragRatio = 5,
    CacheHitRate = 6,
    SafetyErrorRate = 7,
    LogAllocCalls = 8,
    LogLiveBytes = 9,
};

struct Tree {
    uint8_t mode;
    uint8_t feature;
    double threshold;
    double left_value;
    double right_value;
};

static constexpr double BIAS[8] = {
    0.280339903849, 0.29428866545, 0.285576343935, 0.303699426589, 0.282038940822, 0.296176714338, 0.298555930478, 10
};

static constexpr Tree TREES[TREE_COUNT] = {
    {0, SlowPathRatio, 0.94, -0.0376149267183, 0.143478131863},
    {0, SlowPathRatio, 0.94, -0.0244497023669, 0.0932607857107},
    {0, SlowPathRatio, 0.048, -0.0296103304308, 0.0279023310681},
    {0, SlowPathRatio, 0.94, -0.0122385013959, 0.0508536948381},
    {0, MappedLiveRatio, 5375.15, -0.0103469311174, 0.047406332905},
    {0, SlowPathRatio, 0.94, -0.00770254041756, 0.0366763275358},
    {0, MappedLiveRatio, 5375.15, -0.00661838337743, 0.0335100055344},
    {0, SizeEntropy, 1.724, 0.0156339630823, -0.0127330202054},
    {0, MappedLiveRatio, 4776.399, -0.00855195859882, 0.0149327944958},
    {0, SizeEntropy, 0.947, 0.0223591736067, -0.00608432683145},
    {1, SlowPathRatio, 0.94, -0.0205354729895, 0.143524807261},
    {1, InternalFragRatio, 0, -0.0384100360534, 0.0556143080914},
    {1, InternalFragRatio, 0, -0.0249665234347, 0.0361493002594},
    {1, SlowPathRatio, 0.94, -0.00926594787021, 0.0611738617969},
    {1, SlowPathRatio, 0.94, -0.00602286611563, 0.039763010168},
    {1, InternalFragRatio, 0, -0.0108771553375, 0.0152884667028},
    {1, SlowPathRatio, 0.048, -0.00825550549522, 0.0115179760579},
    {1, InternalFragRatio, 0, -0.00591090368196, 0.00821311791772},
    {1, CacheHitRate, 0.220415537489, 0.0169047402786, -0.0019250119748},
    {1, InternalFragRatio, 0.004, -0.00265997947511, 0.0125724653761},
    {2, SlowPathRatio, 0.94, -0.0316008115865, 0.145881275706},
    {2, SlowPathRatio, 0.048, -0.0391999582746, 0.0427931657066},
    {2, SlowPathRatio, 0.94, -0.0163864065996, 0.0798452212114},
    {2, SlowPathRatio, 0.94, -0.0106511642897, 0.0518993937874},
    {2, MappedLiveRatio, 5375.15, -0.00920301135317, 0.0474131333509},
    {2, SlowPathRatio, 0.94, -0.00700481125578, 0.0369556599354},
    {2, MappedLiveRatio, 4776.399, -0.0108558760998, 0.0189671178527},
    {2, MappedLiveRatio, 5375.15, -0.00479585992998, 0.0266317293692},
    {2, SlowPathRatio, 0.94, -0.00438764504274, 0.0249326406195},
    {2, InternalFragRatio, 0.184, 0.0027636925859, -0.0266929581273},
    {3, MappedLiveRatio, 124.121, -0.0411574236635, 0.0217730812269},
    {3, MappedLiveRatio, 124.121, -0.0267523253813, 0.0141525027975},
    {3, CacheHitRate, 0.686127744511, 0.0249304030508, -0.00241101133783},
    {3, SlowPathRatio, 0.048, -0.00436788290321, 0.014015089577},
    {3, SizeEntropy, 2.839, 0.00477836792603, -0.0231826662427},
    {3, MappedLiveRatio, 124.121, -0.0166888272876, 0.00451187187},
    {3, LargeBytesRatio, 0.599, -0.00203783603922, 0.013244647474},
    {3, SizeEntropy, 2.839, 0.00246006846556, -0.0180741932904},
    {3, SlowPathRatio, 0.048, -0.00438342798862, 0.00679499321147},
    {3, InternalFragRatio, 0.004, -0.00189188123848, 0.0101853128906},
    {4, SlowPathRatio, 0.94, -0.0306939230118, 0.114440031376},
    {4, SlowPathRatio, 0.94, -0.0199510499577, 0.0743860203946},
    {4, SlowPathRatio, 0.048, -0.0255383842776, 0.0242317851773},
    {4, InternalFragRatio, 0.184, 0.00325954145439, -0.0577798886644},
    {4, SlowPathRatio, 0.94, -0.00852917177538, 0.0387289489354},
    {4, SizeEntropy, 0.947, 0.0273408739635, -0.00851999270804},
    {4, SlowPathRatio, 0.048, -0.0112395043359, 0.0132331826061},
    {4, SizeEntropy, 1.724, 0.0111082636422, -0.00918569902954},
    {4, MappedLiveRatio, 5375.15, -0.00481016684427, 0.0266392976912},
    {4, MappedLiveRatio, 124.121, 0.0216670386399, -0.00385185763888},
    {5, SlowPathRatio, 0.94, -0.0197028792094, 0.152406403909},
    {5, SlowPathRatio, 0.94, -0.0128068714861, 0.0990641625407},
    {5, SlowPathRatio, 0.048, -0.0220623696362, 0.0342314618001},
    {5, InternalFragRatio, 0, -0.0174226876572, 0.0263599800283},
    {5, SlowPathRatio, 0.94, -0.00618028797751, 0.0431847010115},
    {5, MappedLiveRatio, 5375.15, -0.00491922106541, 0.0334822589377},
    {5, SlowPathRatio, 0.94, -0.004535546146, 0.0297917830304},
    {5, MappedLiveRatio, 5375.15, -0.00361248007671, 0.0233509094606},
    {5, SlowPathRatio, 0.94, -0.00325660135773, 0.0206290269966},
    {5, SizeEntropy, 0.947, 0.0143127367946, -0.00357149427227},
    {6, MappedLiveRatio, 124.121, -0.0428340149452, 0.0157517303709},
    {6, SizeEntropy, 0.947, -0.0231033679175, 0.0120091200204},
    {6, MappedLiveRatio, 124.121, -0.0197559309432, 0.00693153268652},
    {6, InternalFragRatio, 0, 0.010903070102, -0.00980688601453},
    {6, MappedLiveRatio, 124.121, -0.0166574296488, 0.00431366403094},
    {6, InternalFragRatio, 0, 0.00741218385244, -0.00788425832027},
    {6, LargeBytesRatio, 0.599, -0.00246695509692, 0.0129265430632},
    {6, MappedLiveRatio, 124.121, -0.0125581593361, 0.0025152421043},
    {6, InternalFragRatio, 0, 0.00477301058852, -0.00581513390527},
    {6, MappedLiveRatio, 124.121, -0.00983335727448, 0.00181727894823},
};

} // namespace my_ptmalloc::generated_selector_model
